// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzokpugaldeedlxchpzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6b2twdWdhbGRlZWRseGNocHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzIxMDAsImV4cCI6MjA2NzYwODEwMH0.CPQU-v3FgNQa7cR1Dxqkc5msEGJysVtV3vB-Ko_KFTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});